# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Togul < Formula
  desc "Official CLI for Togul feature flags and remote config"
  homepage "https://togul.io"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/togulapp/togul-cli/releases/download/v0.1.0/togul_0.1.0_macOS_x86_64.tar.gz"
      sha256 "59f7cbd9140357ef73a9ed207fad22ab1ded36d40448455376226871638066e8"

      define_method(:install) do
        bin.install "togul"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/togulapp/togul-cli/releases/download/v0.1.0/togul_0.1.0_macOS_arm64.tar.gz"
      sha256 "4f19509c9402e89d5c6da243a08d45baa878e2714efe378494358439db6bfd76"

      define_method(:install) do
        bin.install "togul"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/togulapp/togul-cli/releases/download/v0.1.0/togul_0.1.0_linux_x86_64.tar.gz"
      sha256 "3d8932a7b66fe67c3994eda83299bd3841db934a4f1b3e99451382eb47e3162f"
      define_method(:install) do
        bin.install "togul"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/togulapp/togul-cli/releases/download/v0.1.0/togul_0.1.0_linux_arm64.tar.gz"
      sha256 "4e2356d8c9c239e20fb1d5e01788baa9f036286d4871cf7683f2e7c208c46110"
      define_method(:install) do
        bin.install "togul"
      end
    end
  end

  test do
    system "#{bin}/togul version"
  end
end
